#!/bin/sh

# This script automatically tests the entropy and averages it out:
i=0
while [[ "$i" -le 1000 ]]; do
	 ./genpassrs string --length 20 --encoding extasc | keepassxc-cli estimate | awk '{ print $4 }' >>dataset
	i=$((i + 1))
done
